### PR TITLE
Develop Bill Splitting dApp

### PR DESCRIPTION
**Pull request by bakaoh**
Fix: https://github.com/MyBitFoundation/MyBit-Network.tech/issues/149
Demo: http://128.199.206.130/ (Ropsten testnet)

### CODE REVIEW

**Comment by mybit-coordinator** [comment]
@bakaoh The team is reviewing your PR now, apologies for the delay!

**Comment by ghost** [comment]
Having issues loading "create new" on chrome.

**Comment by bakaoh** [comment]
@AspacehUK - it's seem like the metamask is not unlocked. I added the metamask handler, please retry it

**Comment by mybit-coordinator** [comment]
The bounty has been paid, thank you @bakaoh !

**Pull request merged**
